### PR TITLE
Add collect_and_retry

### PR DESCRIPTION
**Pull request by endor**
I am not entirely happy with making `S` `:Clone`, but I couldn't figure out a better way to make this work.

### CODE REVIEW

**Comment by softprops** [comment]
Does this obviate the motivation to use `collect`. Really want to aim for an api with a small surface area where each area has common usecases. If `collect` was not helpful and motivated another form of collect, is there a way to collapse these into one in a way that is maximally useful. 

I feel like I need to stew on this a bit. There's definitely something here but Im just not sure what the right interface is for it yet

**Comment by endor** [comment]
I suppose for our use case, we'll probably go with `collect_and_retry`, since there will be the potential for errors we want to catch. Or to put it more concretely, while we might have unprocessed keys in the Dynamo success response, we might get provisioned throughput exceeded errors when trying to fetch those unprocessed keys and would like to retry again. So we _could_ remove the `collect` and just keep the `collect_and_retry`, if a small surface area is a goal.

**Comment by endor** [comment]
I'll be on vacation for the next couple of weeks. I can fix any issues that might arise after that.

**Comment by softprops** [comment]
I'll merge this but might make some changes after. Check in when you get back.  Enjoy your vacation!

**Comment by endor** [comment]
So.. where should we go with this? Can a new version be released or should we still do some changes?

**Pull request merged**
